<?php

require_once dirname(__FILE__) . '/includes/exo.field.inc';
require_once dirname(__FILE__) . '/includes/exo.field.admin.inc';

/**
 * Implements hook_menu
 *
 * @author JaceRider
 */
function exo_menu(){
  $items['exo/frame'] = array(
    'page callback' => 'exo_frame_view',
    'delivery callback' => 'exo_deliver_html_page',
    'access arguments' => array('access content'),
    'file' => 'includes/exo.frame.inc',
    'type' => MENU_CALLBACK
  );
  $items['exo/link'] = array(
    'title' => 'Link',
    'page callback' => 'exo_link_view',
    'theme callback' => 'ajax_base_page_theme',
    'access arguments' => array('access content'),
    'file' => 'includes/exo.link.inc',
  );
  $items['admin/config/content/exo'] = array(
    'title' => 'eXo Editor',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('exo_settings'),
    'access arguments' => array('administer exo'),
    'file' => 'includes/exo.admin.inc',
    'description' => t('Configure the eXo editor.')
  );
  $items['admin/config/content/exo/settings'] = array(
    'title' => 'Settings',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => -10
  );
  return $items;
}

/**
 * Implements hook_permission().
 */
function exo_permission() {
  return array(
    'administer exo' => array(
      'title' => t('Administer eXo Editor'),
      'description' => t('Perform administration tasks for the eXo editor.'),
    ),
  );
}

/**
 * Implements hook_theme().
 *
 * @author JaceRider
 */
function exo_theme() {
  return array(
    'exo_frame' => array(
      'variables' => array(),
      'file' => 'theme/exo.theme.inc',
      'template' => 'theme/exo.frame',
    ),
  );
}

/**
 * Add all JavaScript needed for the editor to work.
 */
function exo_add_js($settings = NULL) {
  drupal_add_library('system', 'ui', FALSE);
  drupal_add_library('system', 'ui.widget', FALSE);
  drupal_add_library('system', 'drupal.ajax');
  drupal_add_library('system', 'jquery.form');
  drupal_add_library('exo', 'exo', FALSE);
  if($settings && is_array($settings)){
    drupal_add_js(array('exo' => array($settings['id'] => $settings)), 'setting');
  }
}

/**
 * Add all JavaScript needed for the editor to work.
 */
function exo_frame_add_js($settings = NULL) {
  drupal_add_library('system', 'ui', FALSE);
  drupal_add_library('system', 'ui.widget', FALSE);
  // drupal_add_library('system', 'ui.draggable', FALSE);
  // drupal_add_library('system', 'ui.droppable', FALSE);
  drupal_add_library('system', 'drupal.ajax');
  drupal_add_library('system', 'jquery.form');
  drupal_add_library('exo', 'exo_frame', FALSE);
}

/**
 * Implements hook_js_alter().
 */
function exo_js_alter(&$js) {
  // if(arg(0) == 'exo' && arg(1) == 'frame'){
  //   foreach($js as $path => $data){
  //     if(strpos($path, 'webfont_loader') !== false) continue;
  //     if(strpos($path, 'drupal.js') !== false) continue;
  //     if(strpos($path, 'jquery.js') !== false) continue;
  //     if(strpos($path, 'jquery.once.js') !== false) continue;
  //     if(strpos($path, 'ajax.js') !== false) continue;
  //     if(strpos($path, 'jquery.form.js') !== false) continue;
  //     if($data['type'] != 'file') continue;
  //     unset($js[$path]);
  //   }
  // }
}

/**
 * Implements hook_library().
 */
function exo_library() {
  $path = drupal_get_path('module', 'exo');
  $libraries['exo'] = array(
    'title' => 'eXo',
    'version' => '0.1',
    'js' => array(
      // $path.'/js/exo.rangy.js' => array(),
      $path.'/js/exo.modernizr.js' => array(),
      // $path.'/js/exo.hallo.js' => array(),
      // $path.'/js/exo.dragondrop.js' => array(),
      // $path.'/js/exo.showdown.js' => array(),
      // $path.'/js/exo.marked.js' => array(),
      // $path.'/js/exo.to-markdown.js' => array(),
      // $path.'/js/exo.downshow.js' => array(),
      // $path.'/js/bootstrap/dropdown.js' => array(),
      // $path.'/js/bootstrap/tab.js' => array(),
      $path.'/js/exo.min.js' => array('scope'=>'footer'),
    ),
    'css' => array(
      $path . '/css/exo.css' => array(
        'type' => 'file',
        'media' => 'screen',
      ),
      'http://fonts.googleapis.com/css?family=Open+Sans+Condensed:300,300italic,700' => array(
        'type' => 'file',
        'media' => 'screen',
      )
      // $path . '/css/application.css' => array(
      //   'type' => 'file',
      //   'media' => 'screen',
      // ),
    )
  );
  $libraries['exo_frame'] = array(
    'title' => 'eXo',
    'version' => '0.1',
    'js' => array(
      // $path.'/js/exo.rangy.js' => array(),
      $path.'/js/exo.modernizr.js' => array(),
      $path.'/js/ckeditor/ckeditor.js' => array(),
      // $path.'/js/exo.hallo.min.js' => array(),
      $path.'/js/exo.frame.min.js' => array('scope'=>'footer'),
    ),
    'css' => array(
      $path . '/css/exo.css' => array(
        'type' => 'file',
        'media' => 'screen',
      ),
      'http://fonts.googleapis.com/css?family=Open+Sans+Condensed:300,300italic,700' => array(
        'type' => 'file',
        'media' => 'screen',
      )
      // $path . '/css/application.css' => array(
      //   'type' => 'file',
      //   'media' => 'screen',
      // ),
    )
  );

  return $libraries;
}

/**
 * AJAX Tool for inserting content into an eXo pane.
 *
 * @author JaceRider
 */
function ajax_command_exo_pane($html, $title = NULL, $settings = NULL) {
  $title = empty($title) ? drupal_get_title() : $title;
  $output = '<div id="exo-pane-inner">';
  if($title){
    $output .= '<div id="exo-pane-title">' . $title . '</div>';
  }
  if($message = theme('status_messages')){
    $output .= '<div id="exo-pane-messages">' . $message . '</div>';
  }
  $output .= $html;
  $output .= '</div>';
  return array(
    'command' => 'exoPane',
    'data' => $output,
    'settings' => $settings,
  );
}

/**
 * AJAX tool for hiding the eXo pane.
 */
function ajax_command_exo_pane_hide() {
  return array(
    'command' => 'exoPaneHide',
  );
}
