<?php

/**
 * Implements exo_settings_form_alter().
 */
function exo_breakpoint_exo_settings_form_alter(&$form, $defaults){
  $form['settings']['breakpoint'] = array(
    '#type' => 'checkbox',
    '#title' => t('Enable breakpoint previews'),
    '#default_value' => !empty($defaults['breakpoint']) ? 1 : 0
  );
}

/**
 * Implements exo_process_widget_alter().
 */
function exo_breakpoint_exo_process_widget_alter(&$element, &$settings, $context){

  if(!empty($context['instance']['settings']['exo']['settings']['breakpoint'])){
    $settings['plugins']['exoBreakpoint'] = 1;
    $settings['sidebar'] = TRUE;
  }
}

/**
 * Implements hook_exo_frame().
 */
function exo_breakpoint_exo_frame(){
  drupal_add_js(drupal_get_path('module','exo_breakpoint') . '/js/exo_breakpoint.min.js', array('scope'=>'footer'));
}
